### PR TITLE
refactor: bump basic-utils

### PR DESCRIPTION
**Pull request by diegomura**
Towards using same lib versions in client

### CODE REVIEW

**Comment by mvayngrib** [comment]
lint failing

**Comment by diegomura** [comment]
Same issue that lead to bumping eslint in hydra. I might need to do the same in this monorepo

**Comment by mvayngrib** [comment]
@diegomura what's the status here?

**Comment by diegomura** [comment]
This fails because of eslint again 😞  Need to bump to eslint@9 here, will try to do soon

**Comment by ChALkeR** [comment]
just disable the prefer-basic-utils eslint rule, it's trying to synchronously require basic-utils apparently
or add basic-utils@2 dev-dep to the top-level `package.json` and check if that does the trick

anyway, not having that lint rule for 2 packages here is better than not having basic-utils update

**Comment by mvayngrib** [comment]
we'll be absorbing this repo into hydra in a few months, so i wouldn't waste too much time on lint setup @diegomura , disabling the rule sounds fine

**Comment by diegomura** [comment]
Then definitely not worths bumping to eslint9 here. We can bump basic-utils once the merge happens

**Comment by ChALkeR** [comment]
here, i fixed it

**Comment by diegomura** [comment]
Sounds good. Didn't download the other messages when I replied above. You guys are too fast

**Review by ChALkeR — APPROVED** [review]

**Review by mvayngrib — APPROVED** [review]

**Pull request merged**
