### PR TITLE
feat: add zilliqa schnorr signing (again)

### PR DESCRIPTION
**Pull request by feri42**
Cherry picked #185  from master, to be released without the post 7.4 upgrades.

### CODE REVIEW

**Review by sparten11740 — APPROVED** [review]

**Comment by feri42** [comment]
How can I release a version of keychain from the `[keychain-7.4.x](https://github.com/ExodusMovement/exodus-oss/tree/keychain-7.4.x)` branch?

**Comment by kewde** [comment]
@feri42 try manually releasing it

```
yarn
cd features/keychain
npm publish
```

**Comment by feri42** [comment]
> @feri42 try manually releasing it

Doesn't work out-of-the-box:
```
npm error code E404
npm error 404 Not Found - PUT https://registry.npmjs.org/@exodus%2fkeychain - Not found
npm error 404
npm error 404  '@exodus/keychain@7.4.2' is not in this registry.
```

**Comment by sparten11740** [comment]
@mvayngrib you are admin in this repo right? could you protect the branch `keychain-7.4.x` with the default ruleset, so we can publish from it?

**Comment by feri42** [comment]
I switched to the existing `@exodus/keychain-7.4` branch. And was able to publish 7.4.3 using the github workflow.

**Comment by feri42** [comment]
Also, I've deleted `keychain-7.4.x`

**Pull request merged**
